sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.20.1

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker build -t robhurley/tablebooker_bookings:$(docker images | awk '($1 == "robhurley/tablebooker_bookings") {print $2 += .01; exit}')  bookings
  - docker build -t robhurley/tablebooker_customers:$(docker images | awk '($1 == "robhurley/tablebooker_customers") {print $2 += .01; exit}')  customers
  - docker build -t robhurley/tablebooker_frontend:$(docker images | awk '($1 == "robhurley/tablebooker_frontend") {print $2 += .01; exit}')  frontend
  - docker build -t robhurley/tablebooker_owners:$(docker images | awk '($1 == "robhurley/tablebooker_owners") {print $2 += .01; exit}')  owners
  - docker build -t robhurley/tablebooker_restaurants:$(docker images | awk '($1 == "robhurley/tablebooker_restaurants") {print $2 += .01; exit}')  restaurants

script:
  - bash docker_push
