version: '3.2'

services:

  database:
    image: "mysql"
    container_name: tablebooker_database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
    labels:
      - traefik.enable=false
    networks:
      - internal
      - traefik

  circuit_breaker:
    image: traefik
    container_name: circuit_breaker
    ports:
      - 80:80
      - 8080:8080
    deploy:
      placement:
        constraints:
          - node.role==manager
    networks:
      - internal
      - traefik

  bookings:
    image: "robhurley/tablebooker_bookings"
    container_name: tablebooker_bookings
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/HealthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - "database:mysql"
    labels:
      - traefik.backend=bookings
      - traefik.docker.network=traefik
      - traefik.backend.maxconn.amount=10
      - traefik.backend.loadbalancer.swarm=true
      - traefik.backend.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.5
      - traefik.port=4000
    networks:
      - internal
      - traefik

  customers:
    image: "robhurley/tablebooker_customers"
    container_name: tablebooker_customers
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/HealthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - database:mysql
    labels:
      - traefik.backend=customers
      - traefik.docker.network=traefik
      - traefik.backend.maxconn.amount=10
      - traefik.backend.loadbalancer.swarm=true
      - traefik.backend.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.5
      - traefik.port=5000
    networks:
      - internal
      - traefik
     
  owners:
    image: "robhurley/tablebooker_owners"
    container_name: tablebooker_owners
    ports:
      - "6000:6000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/HealthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - database:mysql
    labels:
      - traefik.backend=owners
      - traefik.docker.network=traefik
      - traefik.backend.maxconn.amount=10
      - traefik.backend.loadbalancer.swarm=true
      - traefik.backend.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.5
      - traefik.port=6000
    networks:
      - internal
      - traefik

  restaurants:
    image: "robhurley/tablebooker_restaurants"
    container_name: tablebooker_restaurants
    ports:
      - "7000:7000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/HealthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - database:mysql
    labels:
      - traefik.backend=restaurants
      - traefik.docker.network=traefik
      - traefik.backend.maxconn.amount=10
      - traefik.backend.loadbalancer.swarm=true
      - traefik.backend.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.5
      - traefik.port=7000
    networks:
      - internal
      - traefik

  frontend:
    image: "robhurley/tablebooker_frontend"
    container_name: tablebooker_frontend
    ports:
      - "8000:8000"
    links:
      - bookings
      - customers
      - owners
      - restaurants
    labels:
      - traefik.enable=false
    networks:
      - internal
      - traefik
