version: '3'

services:

  database:
    image: "mysql"
    container_name: tablebooker_database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=changeme

  bookings:
    image: "robhurley/tablebooker_bookings"
    container_name: tablebooker_bookings
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/HealthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - "database:mysql"

  customers:
    image: "robhurley/tablebooker_customers"
    container_name: tablebooker_customers
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/HealthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - database:mysql
     
  owners:
    image: "robhurley/tablebooker_owners"
    container_name: tablebooker_owners
    ports:
      - "6000:6000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/HealthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - database:mysql

  restaurants:
    image: "robhurley/tablebooker_restaurants"
    container_name: tablebooker_restaurants
    ports:
      - "7000:7000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/HealthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - database:mysql

  frontend:
    image: "robhurley/tablebooker_frontend"
    container_name: tablebooker_frontend
    ports:
      - "8000:8000"
    links:
      - bookings
      - customers
      - owners
      - restaurants
