################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"
################################################################
# Docker configuration backend
################################################################
[docker]
#endpoint = "tcp://127.0.0.1:2375"
domain = "tablebooker"
watch = true
swarmmode = true
# exposedbydefault = false
